// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rating': string;
  'rating--visible': string;
  'ratingStarImage': string;
  'ratingVisible': string;
  'rating__star-image': string;
}
export const cssExports: CssExports;
export default cssExports;
