// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'view-more': string;
  'viewMore': string;
}
export const cssExports: CssExports;
export default cssExports;
