// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card-container': string;
  'card-container__details': string;
  'card-container__image': string;
  'card-container__more-details': string;
  'card-container__quick-view': string;
  'card-container__seperator': string;
  'cardContainer': string;
  'cardContainerDetails': string;
  'cardContainerImage': string;
  'cardContainerMoreDetails': string;
  'cardContainerQuickView': string;
  'cardContainerSeperator': string;
}
export const cssExports: CssExports;
export default cssExports;
