// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sidebar-container': string;
  'sidebar-container__list': string;
  'sidebar-container__list-button': string;
  'sidebar-container__list-item': string;
  'sidebar-container__list-item--active': string;
  'sidebarContainer': string;
  'sidebarContainerList': string;
  'sidebarContainerListButton': string;
  'sidebarContainerListItem': string;
  'sidebarContainerListItemActive': string;
}
export const cssExports: CssExports;
export default cssExports;
