// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'restaurant-container': string;
  'restaurant-container__card-list': string;
  'restaurant-container__title': string;
  'restaurant-container__view-more': string;
  'restaurantContainer': string;
  'restaurantContainerCardList': string;
  'restaurantContainerTitle': string;
  'restaurantContainerViewMore': string;
}
export const cssExports: CssExports;
export default cssExports;
